### ISSUE TITLE
buyoneSkins() function issue

### ISSUE THREAD

**Issue by toofast1** [Trojan13/NodeBitSkins#2]
Hello,

First, I want to congratulate for what you did so far.

I've tried to run the code to see how does it work, however I keep getting the same error message:
`09 03 2017 16:40:38 - Error in buydemSkins
func:buy_item
Uri: https://bitskins.com/api/v1/buy_item/?api_key=MY_API_KEY&code=MY_CODE&item_ids=9402538139&prices=0.01
Error: StatusCodeError: 404 - {"status":"fail","data":{"error_message":"One or more items are undergoing modifications. Please try again in a few minutes."}}`

Is that because the item was already purchased? I've tried to adjust the **crawlBuyTime** variable to 200 and this message still appears. If I modify **crawlBuyTime** to 100, I get an error message saying that the 2FA code is not valid.

If you really know about this issue, please let me know what's causing it.

**Comment by Trojan13** [comment]
Nice to see someone is interested in making this script better.

The error: "One or more items are undergoing modifications. Please try again in a few minutes." appears if the skin is just added by the user. Meaning that the bot tries to fast to buy the skin. A possible solution would be to retry to buy the item until it bought it or another error message appears.

They 2FA Code error occurs if the bot sends the requests to fast. I have tried to avoid it by checking if a new code is needed but it did not work. But if you set the crawlBuyTime to around 600 it should disappear.

**Comment by toofast1** [comment]
I think that using **buy_item** is not a good solution because there are a lot of buyers looking and hunting for the same items. A better solution is to create **buy orders**. Buy orders will always be executed before one-off API call-based purchases.

**Comment by Trojan13** [comment]
I thought about that aswell. But how would you do that. 
The only way I could imagine is cyling through all items you chose, get the lowest **buyorder** for the items and if the price is under a specified amount create one that is 1 cent higher than the existing one. Am I right?

**Comment by toofast1** [comment]
It could work with what you've done so far, but the items that already have buy orders in queue will not be able to be purchased instantly. I've modified your code and it works fine with buy orders. The bad problem is that most of the hot items have a lot of buy orders in queue so you need to wait until you can get one.

If there were no buy orders, this code could generate a lot of income, sadly there are :(
