### ISSUE TITLE
Error run

### ISSUE THREAD

**Issue by S1ROZHA** [Trojan13/NodeBitSkins#6]
![image](https://user-images.githubusercontent.com/20708709/37727417-70bd433c-2d40-11e8-8e64-63f96dec700f.png)
config view 
![image](https://user-images.githubusercontent.com/20708709/37727504-a9be3f74-2d40-11e8-8b4b-d4d59f2a2468.png)

**Comment by Trojan13** [comment]
The general errorhandling is almost none existing. But I fixed this.
This should be fixed with 2014c5b though. It was a problem reading the last trades.
